### ISSUE TITLE
Port list should include all the ports

### ISSUE THREAD

**Issue by silverv** [Zubax/sapog#29]
Related look chat
```
7510:
  _metadata_:
    timestamp: {system: 1641397224.727606, monotonic: 7787.828955}
    priority: optional
    transfer_id: 11
    source_node_id: 22
  publishers:
    sparse_list:
    - {value: 7509}
    - {value: 7510}
  subscribers:
    sparse_list:
    - {value: 180}
    - {value: 135}
    - {value: 136}
  clients:
```
